apiVersion: v1
kind: ConfigMap
metadata:
  name: conteudo-config
  namespace: plataforma
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:5002;http://+:7002"
  JwtSettings__Issuer: "PlataformaEducacional"
  JwtSettings__Audience: "PlataformaEducacional"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  ExternalApis__AuthApi: "http://auth-api:5001"