apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: plataforma
type: Opaque
stringData:
  sql-password: CHANGE_ME
  rabbit-password: CHANGE_ME
  jwt-secret: CHANGE_ME
  auth-conn: "Server=sqlserver;Database=AuthDB;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;"
  conteudo-conn: "Server=sqlserver;Database=ConteudoDB;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;"
  alunos-conn: "Server=sqlserver;Database=AlunosDB;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;"
  pagamentos-conn: "Server=sqlserver;Database=PagamentosDB;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;"
