apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: plataforma
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:5004;http://+:7004"

  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"

  JwtSettings__Issuer: "PlataformaEducacional"
  JwtSettings__Audience: "PlataformaEducacional"
