apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: plataforma
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PagamentosDB;User Id=sa;Password=PlataformaEducacional123!;TrustServerCertificate=True;"

  JwtSettings__SecretKey: "PlataformaEducacional123!SuperSecretKey2024@#$"

  RabbitMQ__Username: "admin"
  RabbitMQ__Password: "admin123"
