apiVersion: v1
kind: ConfigMap
metadata:
  name: alunos-api-config
  namespace: plataforma
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:5003;http://+:7003"
  JwtSettings__Issuer: "PlataformaEducacional"
  JwtSettings__Audience: "PlataformaEducacional"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  ExternalApis__ConteudoApi: "http://conteudo-api:7002"
