apiVersion: v1
kind: Secret
metadata:
  name: alunos-api-secret
  namespace: plataforma
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=AlunosDB;User Id=sa;Password=PlataformaEducacional123!;TrustServerCertificate=True;"
  RabbitMQ__Username: "admin"
  RabbitMQ__Password: "admin123"
