apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: plataforma
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:5001;http://+:7001"
  JwtSettings__Issuer: "PlataformaEducacional"
  JwtSettings__Audience: "PlataformaEducacional"
  JwtSettings__ExpiryMinutes: "15"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
